# Generated by Django 5.0.7 on 2024-07-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('manufacturer', models.CharField(max_length=255)),
                ('aperture', models.DecimalField(decimal_places=2, max_digits=10)),
                ('focal_length', models.IntegerField()),
                ('focal_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
